version: '3.8'

services:
  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
